#mercure:
#    hubs:
#        default:
#            name: default  # Ajoutez cette ligne pour définir le nom du hub
#           # url: '%env(MERCURE_URL)%'
#            public_url: '%env(MERCURE_PUBLIC_URL)%'
#            jwt:
#                secret: '%env(MERCURE_JWT_SECRET)%'
#                publish: '*'