security:
    enable_authenticator_manager: true

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    # Additional configuration for tests
    # when@test:
    #     enable_authenticator_manager: true
    #     user_identity_field: email
    #     password_hashers:
    #         Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
    #             algorithm: auto
    #             cost: 4
    #             time_cost: 3
    #             memory_cost: 10
