controllers:
    resource: ../../src/Controller/
    type: annotation



kernel:
    resource: ../../src/Kernel.php
    type: annotation
app_coach_client_delete:
    path: /coach/client/{id}
    controller: App\Controller\CoachClientController::delete
    methods: POST

