#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes.yaml
table_route:
    path: /user/backend
    controller: App\Controller\UserController::index
profile_picture_upload:
    path: /profile/picture/upload
    controller: App\Controller\ProfileController::uploadPicture
    methods: ['POST']