#index:
#    path: /
#    controller: App\Controller\DefaultController::index
increase_interest:
    path: '/event/{idevent}/increase-interest'
    controller: 'App\Controller\EvenementController::increaseInterest'
    
make_reservation:
    path: '/event/{idevent}/make-reservation'
    controller: 'App\Controller\EvenementController::makeReservation'

app_event_show:
    path: '/event/{idevent}/reservations'
    controller: 'App\Controller\EvenementController::showReservations'
    # methods: ['GET']

    # config/routes.yaml

search_endpoint:
    path: /search-endpoint
    controller: App\Controller\EvenementController::search
    methods: ['POST']

event_pdf:
    path: /event/{idevent}/pdf
    controller: App\Controller\EvenementController::generateEventPdfnow

app_eventreservation_detect_cin:
    path: reservation/detect-cin/{idevent}
    controller: App\Controller\EventreservationController::detectCIN
    methods: ['POST','GET']



