#index:
#    path: /
 #   controller: App\Controller\SalleController::index
# config/routes.yaml
table_route:
    path: /user/backend
    controller: App\Controller\UserController::index

app_seance_new:
    path: '/seance/{idS}/new-seance'
    controller: 'App\Controller\SalleController::newseance'
